In [4]:
import os
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks

In [3]:
path = '../documents/data/1617480254.9367738/'

df = pd.read_csv(f'{path}file_1.csv', index_col=0)
df

,event_0,event_1,event_2,event_3,event_4,event_5,event_6,event_7,event_8,event_9,...,event_92,event_93,event_94,event_95,event_96,event_97,event_98,event_99,event_100,event_101
time_epoch,1.617480e+09,1.617480e+09,1.617480e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,...,1.617492e+09,1.617492e+09,1.617492e+09,1.617492e+09,1.617492e+09,1.617492e+09,1.617492e+09,1.617493e+09,1.617493e+09,1.617493e+09
0,5.200000e+01,5.200000e+01,5.200000e+01,5.100000e+01,5.400000e+01,5.400000e+01,5.200000e+01,5.000000e+01,5.200000e+01,5.000000e+01,...,5.200000e+01,5.200000e+01,5.100000e+01,5.400000e+01,5.100000e+01,5.200000e+01,5.300000e+01,5.200000e+01,5.200000e+01,5.200000e+01
1,5.400000e+01,5.200000e+01,5.100000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.400000e+01,5.000000e+01,5.200000e+01,...,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.100000e+01,5.300000e+01,5.100000e+01,5.200000e+01,5.300000e+01,5.200000e+01
2,5.100000e+01,5.200000e+01,5.100000e+01,5.100000e+01,4.900000e+01,5.200000e+01,5.500000e+01,5.400000e+01,5.200000e+01,5.200000e+01,...,5.200000e+01,5.300000e+01,5.000000e+01,5.300000e+01,5.200000e+01,5.000000e+01,5.200000e+01,5.400000e+01,5.200000e+01,5.300000e+01
3,5.300000e+01,5.400000e+01,5.200000e+01,5.300000e+01,5.200000e+01,5.100000e+01,5.200000e+01,5.100000e+01,5.200000e+01,5.400000e+01,...,5.300000e+01,5.300000e+01,5.200000e+01,4.900000e+01,5.400000e+01,5.300000e+01,5.300000e+01,5.400000e+01,5.200000e+01,5.400000e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,5.000000e+01,5.400000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.400000e+01,5.500000e+01,...,5.400000e+01,5.300000e+01,5.200000e+01,5.300000e+01,5.300000e+01,5.000000e+01,5.200000e+01,5.300000e+01,4.900000e+01,5.200000e+01
2496,5.300000e+01,5.400000e+01,5.000000e+01,5.200000e+01,5.100000e+01,5.300000e+01,5.400000e+01,5.300000e+01,5.300000e+01,5.300000e+01,...,5.500000e+01,5.500000e+01,5.100000e+01,5.200000e+01,5.100000e+01,5.400000e+01,5.200000e+01,5.200000e+01,5.400000e+01,5.200000e+01
2497,5.200000e+01,5.300000e+01,5.200000e+01,5.300000e+01,5.000000e+01,5.300000e+01,5.400000e+01,5.400000e+01,5.200000e+01,5.100000e+01,...,5.300000e+01,5.300000e+01,5.100000e+01,5.200000e+01,5.200000e+01,5.100000e+01,5.300000e+01,5.500000e+01,5.600000e+01,5.300000e+01
2498,5.200000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.200000e+01,5.300000e+01,...,5.300000e+01,5.300000e+01,5.100000e+01,5.300000e+01,5.100000e+01,5.100000e+01,5.300000e+01,5.200000e+01,5.200000e+01,5.100000e+01
2499,5.300000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.400000e+01,5.300000e+01,5.100000e+01,5.600000e+01,5.300000e+01,5.400000e+01,...,5.100000e+01,5.300000e+01,5.100000e+01,5.400000e+01,5.400000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.300000e+01

In [15]:
files = os.listdir(path)
for i in range(len(files)):
    file = files[i]
    if 'csv' not in file:
        files.pop(i)

In [26]:
waveforms = pd.DataFrame()
for i in range(len(files)):
    file = files[i]
    df = pd.read_csv(f"{path}{file}", index_col=0)
    waveforms = pd.concat([waveforms, df], axis=1)
waveforms.columns = [ ('event_'+str(i)) for i in range(waveforms.shape[1]) ]

,event_0,event_1,event_2,event_3,event_4,event_5,event_6,event_7,event_8,event_9,...,event_3008,event_3009,event_3010,event_3011,event_3012,event_3013,event_3014,event_3015,event_3016,event_3017
time_epoch,1.617480e+09,1.617480e+09,1.617480e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,1.617481e+09,...,1.617596e+09,1.617597e+09,1.617597e+09,1.617597e+09,1.617597e+09,1.617597e+09,1.617597e+09,1.617597e+09,1.617597e+09,1.617597e+09
0,5.200000e+01,5.200000e+01,5.200000e+01,5.100000e+01,5.400000e+01,5.400000e+01,5.200000e+01,5.000000e+01,5.200000e+01,5.000000e+01,...,5.000000e+01,5.400000e+01,5.100000e+01,5.200000e+01,5.400000e+01,5.200000e+01,5.200000e+01,5.400000e+01,5.200000e+01,5.200000e+01
1,5.400000e+01,5.200000e+01,5.100000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.400000e+01,5.000000e+01,5.200000e+01,...,5.200000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.400000e+01,5.500000e+01,5.300000e+01,5.400000e+01,5.300000e+01,5.300000e+01
2,5.100000e+01,5.200000e+01,5.100000e+01,5.100000e+01,4.900000e+01,5.200000e+01,5.500000e+01,5.400000e+01,5.200000e+01,5.200000e+01,...,5.300000e+01,5.100000e+01,5.000000e+01,5.100000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.100000e+01,5.100000e+01,5.400000e+01
3,5.300000e+01,5.400000e+01,5.200000e+01,5.300000e+01,5.200000e+01,5.100000e+01,5.200000e+01,5.100000e+01,5.200000e+01,5.400000e+01,...,5.400000e+01,5.200000e+01,5.300000e+01,5.100000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.200000e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,5.000000e+01,5.400000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.400000e+01,5.500000e+01,...,5.300000e+01,5.300000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.000000e+01,5.400000e+01,5.200000e+01,5.200000e+01,5.300000e+01
2496,5.300000e+01,5.400000e+01,5.000000e+01,5.200000e+01,5.100000e+01,5.300000e+01,5.400000e+01,5.300000e+01,5.300000e+01,5.300000e+01,...,5.300000e+01,5.300000e+01,5.200000e+01,5.300000e+01,5.200000e+01,5.300000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.100000e+01
2497,5.200000e+01,5.300000e+01,5.200000e+01,5.300000e+01,5.000000e+01,5.300000e+01,5.400000e+01,5.400000e+01,5.200000e+01,5.100000e+01,...,5.100000e+01,5.300000e+01,5.300000e+01,5.200000e+01,5.400000e+01,5.100000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.000000e+01
2498,5.200000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.300000e+01,5.200000e+01,5.200000e+01,5.300000e+01,5.200000e+01,5.300000e+01,...,5.300000e+01,5.300000e+01,5.300000e+01,5.400000e+01,5.300000e+01,5.200000e+01,5.300000e+01,5.400000e+01,5.300000e+01,5.400000e+01
2499,5.300000e+01,5.200000e+01,5.200000e+01,5.200000e+01,5.400000e+01,5.300000e+01,5.100000e+01,5.600000e+01,5.300000e+01,5.400000e+01,...,5.200000e+01,5.300000e+01,5.500000e+01,5.200000e+01,5.300000e+01,5.400000e+01,5.400000e+01,5.200000e+01,5.300000e+01,5.300000e+01

In [29]:
waveforms.to_csv(f"{path}{waveforms.shape[1]}_events.csv")