In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from scipy.integrate import simps

In [2]:
'''Lendo arquivo das waveforms'''

waveform = pd.read_csv(
    '5555_eventos-edit.csv', 
    index_col = 0
                      ) # importa como waveform vs sample
waveform

,event_0,event_1,event_2,event_3,event_4,event_5,event_6,event_7,event_8,event_9,...,event_5546,event_5547,event_5548,event_5549,event_5550,event_5551,event_5552,event_5553,event_5554,time
0,56.0,56.0,56.0,53.0,55.0,55.0,54.0,54.0,54.0,54.0,...,54.0,53.0,53.0,51.0,51.0,51.0,51.0,51.0,51.0,0
1,55.0,55.0,55.0,53.0,55.0,55.0,54.0,54.0,54.0,54.0,...,52.0,52.0,52.0,52.0,51.0,51.0,51.0,51.0,51.0,1
2,53.0,53.0,53.0,51.0,53.0,53.0,55.0,55.0,55.0,55.0,...,53.0,53.0,53.0,50.0,55.0,55.0,55.0,55.0,55.0,2
3,53.0,53.0,53.0,52.0,53.0,53.0,54.0,54.0,54.0,54.0,...,53.0,53.0,53.0,50.0,55.0,55.0,55.0,55.0,55.0,3
4,54.0,54.0,54.0,53.0,55.0,55.0,55.0,55.0,55.0,55.0,...,51.0,53.0,53.0,52.0,54.0,54.0,54.0,54.0,54.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,53.0,53.0,53.0,54.0,55.0,55.0,22.0,22.0,22.0,22.0,...,54.0,50.0,50.0,50.0,52.0,52.0,52.0,52.0,52.0,2495
2496,55.0,55.0,55.0,54.0,56.0,56.0,14.0,14.0,14.0,14.0,...,50.0,51.0,51.0,53.0,51.0,51.0,51.0,51.0,51.0,2496
2497,52.0,52.0,52.0,53.0,53.0,53.0,37.0,37.0,37.0,37.0,...,53.0,51.0,51.0,53.0,52.0,52.0,52.0,52.0,52.0,2497
2498,52.0,52.0,52.0,53.0,54.0,54.0,51.0,51.0,51.0,51.0,...,52.0,53.0,53.0,52.0,52.0,52.0,52.0,52.0,52.0,2498
2499,53.0,53.0,53.0,52.0,55.0,55.0,47.0,47.0,47.0,47.0,...,53.0,52.0,52.0,52.0,54.0,54.0,54.0,54.0,54.0,2499

In [3]:
event = waveform['event_75']

In [4]:
def peak_finder(_s): # peak_finder se aplica em data frames com valores dp eixo y
    _s *= -1 # CUIDADO: aparentemente, isso muda o df. Tenha certeza que irá desfazer isso depois
    
    # get the actual peaks
    peaks, _ = find_peaks(_s, height=50) # height é um parâmetro decidido
    
    # multiply back for plotting purposes
    _s *= -1
    
    
    return(peaks)

In [5]:
def delta_signal(y_values): # esta função retorna os valores no eixo x; aplicado em elementos de 1D
    
    VA_baseLine = 5 # valor "aleatório" para saber se o número em questão está fora da base-line
    
    delta = [ 
        i for i in range( len(y_values) - 1 ) 
           if ( abs(y_values[i] - y_values[i+1]) > VA_baseLine) 
            ] # é interessante calcular com base no módulo
    return(delta)

In [6]:
def contorno_pulso(_s):
    
    '''
    encontra os picos
    '''
    
    peak = peak_finder(_s)
    
    evento          = pd.DataFrame( delta_signal(_s) )
    evento.columns  = ['coluna'] # nome genérico, para ser chamável depois 
    
    
    
    '''
    determina a largura de cada pulso no eixo x
    '''
    
    largura_max_esperada = 100 # define a abertura de uma janela para procurar o pulso ali dentro
    
    lista = []
    for i in range(2):
        
        s = evento.query( 
            '(coluna > @peak[@i] - @largura_max_esperada/2) and (coluna < @peak[@i] + @largura_max_esperada/2)'
                        )['coluna']
        # este objeto é uma Series
        
        lista.append( s.min() )
        lista.append( s.max() ) # transformar em lista serve para facilitar o plot gráfico    

            
              
    '''
    cria o data frame com os contornos máximo e mínimo do pulso em x e y
    '''
    
    df = pd.DataFrame(_s)
    df.columns = ['coluna'] # nome genérico, para ser chamável depois
    
    limites_largura_pulsos = pd.DataFrame( df.query('@lista')['coluna'] ).reset_index() 
    # este método anterior acaba por mover os valores do index para uma coluna e resetar o index principal
    # daí, é só renomear o index e as colunas
            
    limites_largura_pulsos.index   = ['min_1', 'max_1', 'min_2', 'max_2']
    limites_largura_pulsos.columns = ['pulso_x', 'pulso_y']


    '''
    remodela o data frame com os valores em x e y para cada um dos primeiros pulsos
    '''
    
    aux = []
    for i in range(0,3,2): # é um loop para atuar apenas duas vezes: 0,1 e 2,3
        s = df.query(" index >= @lista[@i] and index <= @lista[@i+1] ")['coluna']
        aux.append(s)
        
    pulsos = pd.concat(aux, axis = 1).reset_index() # coordenada x, primeiro pulso, segundo pulso
    pulsos.columns = ['time', 'pulso_1', 'pulso_2']
    
    
    
    
    return(pulsos)

In [7]:
def integral_pulso(_df): # df = ['time', 'pulso_1', 'pulso_2']
    
    aux = []
    for i in range(len( _df.colums) ):
        integral = simps(    _df[ _df.columns[i] ].dropna(),    dx = 1     )
        aux.append(integral)
    
    return(aux)

In [8]:
contorno_pulso(event)

    time  pulso_1  pulso_2
0     91     52.0      NaN
1     92     37.0      NaN
2     93    -97.0      NaN
3     94   -127.0      NaN
4     95   -123.0      NaN
5     96     -5.0      NaN
6     97     28.0      NaN
7     98     12.0      NaN
8     99     14.0      NaN
9    100     41.0      NaN
10   101     49.0      NaN
11   102     40.0      NaN
12   103     38.0      NaN
13   104     47.0      NaN
14   105     58.0      NaN
15   106     52.0      NaN
16   107     42.0      NaN
17   108     51.0      NaN
18   109     58.0      NaN
19   110     53.0      NaN
20   111     49.0      NaN
21   112     53.0      NaN
22   113     55.0      NaN
23   114     53.0      NaN
24   115     49.0      NaN
25   116     52.0      NaN
26   117     54.0      NaN
27   118     56.0      NaN
28   119     55.0      NaN
29   120     50.0      NaN
30   121     52.0      NaN
31   122     55.0      NaN
32   123     49.0      NaN
33   124     48.0      NaN
34  1030      NaN     51.0
35  1031      NaN     40.0
36  1032      NaN    -19.0
37  1033      NaN    -51.0
38  1034      NaN    -14.0
39  1035      NaN     23.0
40  1036      NaN     41.0
41  1037      NaN     36.0
42  1038      NaN     38.0
43  1039      NaN     47.0