In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from scipy.integrate import simps

# Lendo arquivo das waveforms

#### O arquivo original já foi parcialmente modificado em relação a linhas e colunas

In [2]:
'''Lendo arquivo das waveforms'''

waveform = pd.read_csv(
    '5555_eventos-edit.csv', 
    index_col = 0
                      ) # importa como waveform vs sample
waveform

,event_0,event_1,event_2,event_3,event_4,event_5,event_6,event_7,event_8,event_9,...,event_5546,event_5547,event_5548,event_5549,event_5550,event_5551,event_5552,event_5553,event_5554,time
0,56.0,56.0,56.0,53.0,55.0,55.0,54.0,54.0,54.0,54.0,...,54.0,53.0,53.0,51.0,51.0,51.0,51.0,51.0,51.0,0
1,55.0,55.0,55.0,53.0,55.0,55.0,54.0,54.0,54.0,54.0,...,52.0,52.0,52.0,52.0,51.0,51.0,51.0,51.0,51.0,1
2,53.0,53.0,53.0,51.0,53.0,53.0,55.0,55.0,55.0,55.0,...,53.0,53.0,53.0,50.0,55.0,55.0,55.0,55.0,55.0,2
3,53.0,53.0,53.0,52.0,53.0,53.0,54.0,54.0,54.0,54.0,...,53.0,53.0,53.0,50.0,55.0,55.0,55.0,55.0,55.0,3
4,54.0,54.0,54.0,53.0,55.0,55.0,55.0,55.0,55.0,55.0,...,51.0,53.0,53.0,52.0,54.0,54.0,54.0,54.0,54.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,53.0,53.0,53.0,54.0,55.0,55.0,22.0,22.0,22.0,22.0,...,54.0,50.0,50.0,50.0,52.0,52.0,52.0,52.0,52.0,2495
2496,55.0,55.0,55.0,54.0,56.0,56.0,14.0,14.0,14.0,14.0,...,50.0,51.0,51.0,53.0,51.0,51.0,51.0,51.0,51.0,2496
2497,52.0,52.0,52.0,53.0,53.0,53.0,37.0,37.0,37.0,37.0,...,53.0,51.0,51.0,53.0,52.0,52.0,52.0,52.0,52.0,2497
2498,52.0,52.0,52.0,53.0,54.0,54.0,51.0,51.0,51.0,51.0,...,52.0,53.0,53.0,52.0,52.0,52.0,52.0,52.0,52.0,2498
2499,53.0,53.0,53.0,52.0,55.0,55.0,47.0,47.0,47.0,47.0,...,53.0,52.0,52.0,52.0,54.0,54.0,54.0,54.0,54.0,2499

# Construindo os métodos para a análise de dados

#### 1. Peak_finder 

Auxilia a encontrar todos os picos de uma waveform. No caso, encontra dois picos.

In [3]:
def peak_finder(_s, height): # peak_finder se aplica em data frames com valores dp eixo y
    _s *= -1 # CUIDADO: aparentemente, isso muda o df. Tenha certeza que irá desfazer isso depois
    
    # get the actual peaks
    peaks, _ = find_peaks(_s, height = 40) # height é um parâmetro decidido
    
    # print(peaks)
    
    # multiply back for plotting purposes
    _s *= -1
    
    
    return(peaks)

#### 2. delta_signal

Encontra as diferenças entre elementos lado-a-lado. Serve para avaliar quando estamos começando ou terminando um pulso.

In [4]:
def delta_x(s): # insira uma series na entrada; o valor retornado está em coordenadas do eixo x
    VA_derivada_baseLine = 5  #   flutuação/amplitude máxima da base-line;
                              #   valor arbirtrário para saber se o número em questão está fora da 
                              # base-line; não é exatamente a derivada
    lst = []
    for i in range( len(s) - 1 ): # i = index da series
        if abs(s[i] - s[i+1]) > VA_derivada_baseLine:
            lst.append(i) 
    #print(lst)
        
    return (lst) # o valor retornado está em coordenadas do eixo x

#### 3. contorno_pulso

Encontra os valores dos dois pulsos em cada uma das waveforms. Utiliza as duas funções anteriores. 
Funciona da seguinte maneira: encontra os picos e delimita os entornos. Daí, guarda os pontos interiores do pulso e os devolve.

In [19]:
def contorno_pulso(_s): # recebe uma Series do pandas para começar
    
    
    '''
    Define um recorte de onde se deve buscar um pulso e os seus delimitadores
    '''
    
    VA_1 = 20 # variáveis arbitrárias para definir a largura do pulso
    VA_2 = 80

    peak = peak_finder(_s, height = 50) # encontrar os picos da waveform
    
    s1 = _s[ (peak[0] - VA_1):(peak[0] + VA_2) ] # recortar em volta dos picos
    s2 = _s[ (peak[1] - VA_1):(peak[1] + VA_2) ]
    
    df1 = pd.DataFrame( dict(s1 = s1) ).reset_index() # cria um Data Frame com os valores do recorte
    df1.columns = ['time', 's1']                      # renomeia a coluna do data frame
    df2 = pd.DataFrame( dict(s1 = s2) ).reset_index()
    df2.columns = ['time', 's2']
    
    
    

    '''
    Calcular a "derivada" em cada ponto no entorno, para saber os limitantes do pulso
    Ao terminar, retornar o data frame que contem os valores limitantes do contorno do pulso
    '''  

    indexLim_1 = delta_x( df1['s1'] ) # índices limitantes
    indexLim_2 = delta_x( df2['s2'] )
    
    # redefine os valores para apenas os limitantes do data frame
    df1 = df1.iloc[    [  indexLim_1[0], indexLim_1[-1]  ]    ] 
    df2 = df2.iloc[    [  indexLim_2[0], indexLim_2[-1]  ]    ] 
    
    # print(df2) # series marcada pelas colunas 
    
    
    # da Series original, temos agora o contorno do pulso
    s1 = _s[ df1['time'].iloc[0] : df1['time'].iloc[1]+1 ] # soma 1 para incluir o último termo
    s2 = _s[ df2['time'].iloc[0] : df2['time'].iloc[1]+1 ] 
    
    # print(s2)
    
    pulsos = s1, s2
    
    
    
    
    
    
    return(pulsos) # retorna os dois contornos, um de cada pulso

#### integral_pulso

Calcula a integral do contorno do pulso da waveform utilizando a integração numérica de Simpson.

In [24]:
def integral_pulso(tupla_de_Series): # df = ['time', 'pulso_1', 'pulso_2']
    
    s1, s2  =   tupla_de_Series[0], tupla_de_Series[1]
    
    integral_pulso = [ 
        simps(s1, dx = 1),
        simps(s2, dx = 1)
                ]
    
    return(integral_pulso)

# Análise de dados

#### Translação da base-line

É interessante transladar os pontos e fixar a base line no 0. Podemos fazer isso somando -50 em cada um dos valores de toda a coleção de waveforms. Isso servirá para evitar problemas de 'height' no peak_finder()

In [21]:
'''
Alterando os valores e recolocando na base line = 0
'''

df = waveform.copy(deep = True) # cria uma cópia do dataframe original, para não causar alterações nele
df.iloc[ :  , :waveform.shape[1]-1 ] -= 50 # soma -50 em todo o df, exceto pela última coluna 'time'
df

,event_0,event_1,event_2,event_3,event_4,event_5,event_6,event_7,event_8,event_9,...,event_5546,event_5547,event_5548,event_5549,event_5550,event_5551,event_5552,event_5553,event_5554,time
0,6.0,6.0,6.0,3.0,5.0,5.0,4.0,4.0,4.0,4.0,...,4.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,0
1,5.0,5.0,5.0,3.0,5.0,5.0,4.0,4.0,4.0,4.0,...,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1
2,3.0,3.0,3.0,1.0,3.0,3.0,5.0,5.0,5.0,5.0,...,3.0,3.0,3.0,0.0,5.0,5.0,5.0,5.0,5.0,2
3,3.0,3.0,3.0,2.0,3.0,3.0,4.0,4.0,4.0,4.0,...,3.0,3.0,3.0,0.0,5.0,5.0,5.0,5.0,5.0,3
4,4.0,4.0,4.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,...,1.0,3.0,3.0,2.0,4.0,4.0,4.0,4.0,4.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,3.0,3.0,3.0,4.0,5.0,5.0,-28.0,-28.0,-28.0,-28.0,...,4.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,2.0,2495
2496,5.0,5.0,5.0,4.0,6.0,6.0,-36.0,-36.0,-36.0,-36.0,...,0.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,2496
2497,2.0,2.0,2.0,3.0,3.0,3.0,-13.0,-13.0,-13.0,-13.0,...,3.0,1.0,1.0,3.0,2.0,2.0,2.0,2.0,2.0,2497
2498,2.0,2.0,2.0,3.0,4.0,4.0,1.0,1.0,1.0,1.0,...,2.0,3.0,3.0,2.0,2.0,2.0,2.0,2.0,2.0,2498
2499,3.0,3.0,3.0,2.0,5.0,5.0,-3.0,-3.0,-3.0,-3.0,...,3.0,2.0,2.0,2.0,4.0,4.0,4.0,4.0,4.0,2499

In [22]:
contorno_pulso(waveform.event_75)

(91      52.0
 92      37.0
 93     -97.0
 94    -127.0
 95    -123.0
 96      -5.0
 97      28.0
 98      12.0
 99      14.0
 100     41.0
 101     49.0
 102     40.0
 103     38.0
 104     47.0
 105     58.0
 106     52.0
 107     42.0
 108     51.0
 109     58.0
 110     53.0
 111     49.0
 112     53.0
 113     55.0
 114     53.0
 115     49.0
 116     52.0
 117     54.0
 118     56.0
 119     55.0
 120     50.0
 121     52.0
 122     55.0
 123     49.0
 124     48.0
 Name: event_75, dtype: float64,
 1030    51.0
 1031    40.0
 1032   -19.0
 1033   -51.0
 1034   -14.0
 1035    23.0
 1036    41.0
 1037    36.0
 1038    38.0
 1039    47.0
 Name: event_75, dtype: float64)

In [30]:
%%time
a = df[df.columns[190]]
integral_pulso(contorno_pulso(a))

Wall time: 15 ms

[-301.0, -341.3333333333333]

In [37]:
%%time

'''
Loop para integrar os pulsos em todo o Data Frame
'''

integrais = []
for i in range( waveform.shape[1] - 1  ): # loop para integrar os pulsos em todo o Data Frame
    evento = df[df.columns[i]]
    integrais.append( integral_pulso(contorno_pulso(evento)) )

Wall time: 47.3 s